glowingjade/obsidian-smart-composer

src/utils/vector-db/repository.ts

Use [obsidian api - requestUrl](https://docs.obsidian.md/Reference/TypeScript+API/requestUrl) function to bypass CORS restrictions. Using `fetch` can cause following error:
`Access to fetch at '[https://unpkg.com/@electric-sql/pglite/dist/vector.tar.gz' from origin 'app://obsidian.md' has been blocked by CORS policy: No 'Access-Control-Allow-Origin](https://unpkg.com/@electric-sql/pglite/dist/vector.tar.gz'%20from%20origin%20'app://obsidian.md'%20has%20been%20blocked%20by%20CORS%20policy:%20No%20'Access-Control-Allow-Origin)' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.`

Fix CORS error when fetching pglite resources

---

src/components/chat-view/Chat.tsx
src/utils/embedding.ts
src/utils/llm/exception.ts
src/utils/llm/ollama.ts
src/utils/openSettingsModal.ts
src/utils/vector-db/manager.ts

- Show `OpenSettingsModal` for llm setting errors during embedding generation.
- `VectorDbManager.updateVaultIndex`: If an error occurs during embedding generation, ongoing tasks are aborted.

Handle llm setting errors during embedding generation

---

src/components/chat-view/chat-input/ChatUserInput.tsx
src/components/chat-view/chat-input/plugins/auto-focus/AutoFocusPlugin.tsx

Implemented custom AutoFocusPlugin.
```javascript
if (rootElement !== null && (activeElement === null || !rootElement.contains(activeElement))) {
// Note: preventScroll won't work in Webkit.
rootElement.focus({
preventScroll: true
});
}
```
- In our use case, activeElement (MarkdownView) doesn't contain rootElement (ChatUserInput)

Autofocus input

---

src/ChatView.tsx
src/components/chat-view/Chat.tsx
src/main.ts

- Update the "Open chat" command to create a new chat if the chat view is already open.
- Continue using `openChatView()` for the ribbon icon.

Add open new chat command

---

src/database/DatabaseManager.ts

The unpinned PGlite version was causing a runtime TypeError where ASM_CONSTS[i] was not a function. This pins the version to 0.2.12 across all PGlite assets (`postgres.data`, `postgres.wasm`, and `vector.tar.gz`) to ensure compatibility and resolve the runtime error.

hotfix: pin pglite version to 0.2.12

---

package-lock.json
package.json
src/core/rag/ragEngine.ts
src/database/modules/vector/VectorManager.ts
src/settings/SettingTab.tsx
src/types/settings.test.ts
src/types/settings.ts
src/utils/globUtils.ts

- Added support for excluding files from RAG indexing using glob patterns
- Integrated the `minimatch` package for glob pattern matching
- Updated settings UI to allow users to configure exclusion patterns
- Modified the vector indexing logic to respect exclusion patterns

Add File Exclusion Patterns for RAG Indexing

---

drizzle/0006_rename_vector_tables.sql
drizzle/meta/0006_snapshot.json
drizzle/meta/_journal.json
package-lock.json
package.json
src/components/chat-view/Chat.tsx
src/components/chat-view/chat-input/ModelSelect.tsx
src/constants.ts
src/contexts/llm-context.tsx
src/core/llm/anthropic.ts
src/core/llm/base.ts
src/core/llm/exception.ts
src/core/llm/groq.ts
src/core/llm/manager.ts
src/core/llm/ollama.ts
src/core/llm/openai.ts
src/core/llm/openaiCompatibleProvider.ts
src/core/llm/openaiMessageAdapter.ts
src/core/rag/embedding.ts
src/core/rag/ragEngine.ts
src/database/migrations.json
src/database/modules/vector/VectorRepository.ts
src/database/schema.ts
src/settings/SettingTab.tsx
src/types/embedding.ts
src/types/llm/model.ts
src/types/settings.test.ts
src/types/settings.ts
src/utils/apply.ts
styles.css

- Introduce new model configuration system with provider-specific settings
- Add support for Ollama and OpenAI-compatible services
- Reorganize model IDs to include provider prefix (e.g. openai/, anthropic/, groq/)
- Update settings UI to show provider-specific configuration fields
- Refactor LLM manager and providers to use new model configuration
- Rename vector tables to match new model ID format
- Add migration for vector table renaming
- Model updates
- Add `claude-3.5-haiku` option for apply model
- Remove `llama3-8b (Groq)` option for apply model

refactor: restructure model configuration and settings

---

README.md
drizzle/0007_create_vector_data_gemini_text_embedding_004.sql
drizzle/meta/0007_snapshot.json
drizzle/meta/_journal.json
src/constants.ts
src/core/llm/exception.ts
src/core/rag/embedding.ts
src/core/rag/ragEngine.ts
src/database/migrations.json
src/database/modules/vector/VectorManager.ts
src/database/schema.ts
src/types/embedding.ts

- Add Gemini text-embedding-004 as a new embedding model option
- Add rate limit error handling for embedding API calls
- Update model names to include provider prefix for clarity

feat: add Gemini text-embedding-004 model

---

src/components/chat-view/chat-input/ChatUserInput.tsx
src/components/chat-view/chat-input/ImageUploadButton.tsx
src/components/chat-view/chat-input/LexicalContentEditable.tsx
src/components/chat-view/chat-input/MentionableBadge.tsx
src/components/chat-view/chat-input/ModelSelect.tsx
src/components/chat-view/chat-input/plugins/image/DragDropPastePlugin.tsx
src/components/chat-view/chat-input/plugins/image/ImagePastePlugin.tsx
src/components/chat-view/chat-input/utils/get-metionable-icon.ts
src/core/llm/anthropic.ts
src/core/llm/gemini.ts
src/core/llm/groq.ts
src/core/llm/openaiMessageAdapter.ts
src/types/chat.ts
src/types/llm/request.ts
src/types/mentionable.ts
src/utils/image.ts
src/utils/mentionable.ts
src/utils/promptGenerator.ts
styles.css

This PR adds support for image uploads and display in chat messages, enabling users to include images in their conversations.
- Added image upload button in chat input
- Image paste support via `ImagePastePlugin`
- Preview of uploaded images in the chat interface
- Add support for handling image content in messages across LLM providers

feat: add image support in chat

---

src/utils/fuzzy-search.ts
src/utils/obsidian.test.ts
src/utils/obsidian.ts

this fixes https://github.com/glowingjade/obsidian-smart-composer/issues/130
- Improve search accuracy by considering both file names and paths in fuzzy matching
- Implement folder scoring with distance-based boost

enhance fuzzy search using name and path keys

---

src/components/chat-view/Chat.tsx
src/components/chat-view/ChatListDropdown.tsx

- Auto-focus current conversation in ChatListDropdown
- Close dropdown on select conversation

fix: auto-focus current conversation in ChatListDropdown

---

src/settings/SettingTab.tsx
src/utils/ollama.ts

- Replace text input for Ollama model with dropdown populated from API
- Add automatic model list fetching when base URL changes
https://github.com/user-attachments/assets/5fb98d84-e7c4-4597-973b-40b7c5c6af38

feat: Add dynamic Ollama model selection dropdown

---

src/core/llm/anthropic.ts

Handle following error when empty assistant message is given to anthropic models
```
Failed to generate response Error: 400 {"type":"error","error":{"type":"invalid_request_error","message":"messages.1: all messages must have non-empty content except for the optional final assistant message"}}
```

fix: add empty message filtering for anthropic

---

src/settings/SettingTab.tsx

Thank you for developing such an excellent plugin!
I found ollama model name selection does not work.
The current implementation appears to have two issues:
- fixed in l712-715
- This happens because `dropdown.getValue()` returns nothing if there is no corresponding option.
I should mention that I’m not very familiar with this project or, more generally, with Obsidian plugin development. If there are any conventions or best practices that I’ve overlooked, please know it’s unintentional, and I’d appreciate it if you could point them out.

fix: make ollama model selection work

---

src/components/common/ObsidianToggle.tsx
src/components/settings/ProviderFormModalRoot.tsx
src/constants.ts
src/core/llm/NoStainlessOpenAI.ts
src/core/llm/ollama.ts
src/core/llm/openaiCompatibleProvider.ts
src/types/provider.types.ts

Added "no stainless headers" setting for openai compatible providers.
It'll resolve https://github.com/glowingjade/obsidian-smart-composer/issues/158

add no stainless headers toggle setting for openai compatible provider

---

src/components/chat-view/chat-input/ModelSelect.tsx
src/components/settings/sections/ChatSection.tsx
src/components/settings/sections/ProvidersSection.tsx
src/components/settings/sections/models/ChatModelsSubSection.tsx
src/types/chat-model.types.ts

A new feature has been added to allow users to turn chat models on or off as needed.
Users can toggle the enable button in the settings to switch the chat model between enabled and disabled states.

feat: Added an option to enable/disable chat models.

---

src/database/modules/vector/VectorManager.ts

handle null bytes in chunk content on RAG indexing and throw error

handle null bytes in chunk content on RAG indexing and throw error

---

src/components/settings/sections/RAGSection.tsx

fixes https://github.com/glowingjade/obsidian-smart-composer/issues/261

fix bug: interference with decimal input in RAG > Minimum Similarity settings

---

src/constants.ts
src/settings/schema/migrations/3_to_4.test.ts
src/settings/schema/migrations/3_to_4.ts
src/settings/schema/migrations/index.ts
src/settings/schema/setting.types.ts
src/settings/schema/settings.test.ts

- Update default and recommended chat model from Claude 3.5 to Claude 3.7 Sonnet
- Add Claude 3.7 Sonnet pricing configuration
- Increment settings schema version to 4 and add migration
- Support [extended thinking mode](https://docs.anthropic.com/en/docs/build-with-claude/extended-thinking) for Claude 3.7 Sonnet

feat: upgrade to Claude 3.7 Sonnet as default model

---

src/core/llm/NoStainlessOpenAI.ts
src/core/llm/lmStudioProvider.ts
src/core/llm/ollama.ts
src/core/llm/openaiCompatibleProvider.ts

Fixes issue #337, #353 where embedding requests failed after OpenAI library update. Adding encoding_format parameter restores original behavior for OpenAI-compatible providers.

fix: Add encoding_format: 'float' to embedding requests
